### ISSUE TITLE
Add connectors + define connector locations

### ISSUE THREAD

**Issue by jbwillis** [PyCubed-Mini/avionics-batteryboard#3]
- [x] Add connector footprints to the PCBs
- [x] Define connector locations such that connectors line up between the boards. Reference the spreadsheet for exact connector types [](https://docs.google.com/spreadsheets/d/1i2yN5ufJ_oHtiOwThea0zdWcafgQmKxAroj-7NV7IT0/edit#gid=0)
- [ ]

**Comment by g-savant** [comment]
Finished
